apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mes-backgroundtasks
  name: mes-backgroundtasks
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mes-backgroundtasks
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mes-backgroundtasks
    spec:
      containers:
      - image: nuget.czhipu.com/xnebula/hymson.mes.backgroundtasks:20240724081238
        name: mes-backgroundtasks
        volumeMounts:
          - mountPath: /logs
            name: mes-backgroundtasks-volume
        env:
        - name: DOTNET_ENVIRONMENT
          value: "Production"
        resources: {}
      volumes:
      - name: mes-backgroundtasks-volume
        # 挂载 /data/foo，但仅当该目录已经存在时
        hostPath:
          path: /data/logs # 主机上的目录位置
          type: DirectoryOrCreate # 此字段可选
status: {}