apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: equ-api
  name: equ-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: equ-api
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: equ-api
    spec:
      containers:
      - image: nuget.czhipu.com/xnebula/hymson.mes.equipment.api:20240731200857
        name: equ-api
        volumeMounts:
          - mountPath: /logs
            name: equ-api-volume
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: TZ
          value: "Asia/Shanghai"
        resources: {}
        ports: 
          - name: equ-api-svc        #端口的名称
            containerPort: 80  #容器需要监听的端口号
            hostPort: 20033
      volumes:
      - name: equ-api-volume
        # 挂载 /data/foo，但仅当该目录已经存在时
        hostPath:
          path: /data/logs # 主机上的目录位置
          type: DirectoryOrCreate # 此字段可选
status: {}