apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: sys-api
  name: sys-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sys-api
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sys-api
    spec:
      containers:
      - image: nuget.czhipu.com/xnebula/hymson.mes.system.api:20241118181253
        name: sys-api
        volumeMounts:
          - mountPath: /logs
            name: sys-api-volume
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: TZ
          value: "Asia/Shanghai"
        resources: {}
        ports: 
          - name: sys-api-svc        #端口的名称
            containerPort: 80  #容器需要监听的端口号
            hostPort: 12002
      volumes:
      - name: sys-api-volume
        # 挂载 /data/foo，但仅当该目录已经存在时
        hostPath:
          path: /data/logs # 主机上的目录位置
          type: DirectoryOrCreate # 此字段可选
status: {}